[package]
name = "flexvolume-drivers-psp"
version = "1.0.1"
authors = ["Rafael Fernández López <ereslibre@ereslibre.es>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib"]

[dependencies]
k8s-openapi = { version = "0.25.0", features = ["v1_33"] }
kubewarden-policy-sdk = { version = "0.13.4", default-features = false }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
